/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as kioskLayoutRouteImport } from './routes/(kiosk)/layout'
import { Route as privateLayoutRouteImport } from './routes/(private)/layout'
import { Route as guestauthLayoutRouteImport } from './routes/(guest)/(auth)/layout'
import { Route as privateProfileLayoutRouteImport } from './routes/(private)/profile/layout'
import { Route as kioskScreensPageRouteImport } from './routes/(kiosk)/screens/page'
import { Route as privatehomePageRouteImport } from './routes/(private)/(home)/page'
import { Route as privateBackofficePageRouteImport } from './routes/(private)/backoffice/page'
import { Route as privateProfilePageRouteImport } from './routes/(private)/profile/page'
import { Route as guestauthForgotPasswordPageRouteImport } from './routes/(guest)/(auth)/forgot-password/page'
import { Route as guestauthLoginPageRouteImport } from './routes/(guest)/(auth)/login/page'
import { Route as guestauthResetPasswordPageRouteImport } from './routes/(guest)/(auth)/reset-password/page'
import { Route as kioskScreensAccueilPageRouteImport } from './routes/(kiosk)/screens/accueil/page'
import { Route as kioskScreensBornePageRouteImport } from './routes/(kiosk)/screens/borne/page'
import { Route as kioskScreensDiscoursPageRouteImport } from './routes/(kiosk)/screens/discours/page'
import { Route as kioskScreensOperateurPageRouteImport } from './routes/(kiosk)/screens/operateur/page'
import { Route as privateBackofficeConversationsPageRouteImport } from './routes/(private)/backoffice/conversations/page'
import { Route as privateBackofficeGuestsPageRouteImport } from './routes/(private)/backoffice/guests/page'
import { Route as privateBackofficeHandoffsPageRouteImport } from './routes/(private)/backoffice/handoffs/page'
import { Route as privateBackofficeQrSheetPageRouteImport } from './routes/(private)/backoffice/qr-sheet/page'
import { Route as privateProfilePrivacyPageRouteImport } from './routes/(private)/profile/privacy/page'
import { Route as privateProfileSecurityPageRouteImport } from './routes/(private)/profile/security/page'
import { Route as publicITokenPageRouteImport } from './routes/(public)/i/$token/page'
import { Route as privateBackofficeConversationsConversationIdPageRouteImport } from './routes/(private)/backoffice/conversations/$conversationId/page'
import { Route as privateBackofficeGuestsGuestIdPageRouteImport } from './routes/(private)/backoffice/guests/$guestId/page'

const kioskLayoutRoute = kioskLayoutRouteImport.update({
  id: '/(kiosk)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestauthLayoutRoute = guestauthLayoutRouteImport.update({
  id: '/(guest)/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateProfileLayoutRoute = privateProfileLayoutRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => privateLayoutRoute,
} as any)
const kioskScreensPageRoute = kioskScreensPageRouteImport.update({
  id: '/screens/',
  path: '/screens/',
  getParentRoute: () => kioskLayoutRoute,
} as any)
const privatehomePageRoute = privatehomePageRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateBackofficePageRoute = privateBackofficePageRouteImport.update({
  id: '/backoffice/',
  path: '/backoffice/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateProfilePageRoute = privateProfilePageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateProfileLayoutRoute,
} as any)
const guestauthForgotPasswordPageRoute =
  guestauthForgotPasswordPageRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => guestauthLayoutRoute,
  } as any)
const guestauthLoginPageRoute = guestauthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => guestauthLayoutRoute,
} as any)
const guestauthResetPasswordPageRoute =
  guestauthResetPasswordPageRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => guestauthLayoutRoute,
  } as any)
const kioskScreensAccueilPageRoute = kioskScreensAccueilPageRouteImport.update({
  id: '/screens/accueil/',
  path: '/screens/accueil/',
  getParentRoute: () => kioskLayoutRoute,
} as any)
const kioskScreensBornePageRoute = kioskScreensBornePageRouteImport.update({
  id: '/screens/borne/',
  path: '/screens/borne/',
  getParentRoute: () => kioskLayoutRoute,
} as any)
const kioskScreensDiscoursPageRoute =
  kioskScreensDiscoursPageRouteImport.update({
    id: '/screens/discours/',
    path: '/screens/discours/',
    getParentRoute: () => kioskLayoutRoute,
  } as any)
const kioskScreensOperateurPageRoute =
  kioskScreensOperateurPageRouteImport.update({
    id: '/screens/operateur/',
    path: '/screens/operateur/',
    getParentRoute: () => kioskLayoutRoute,
  } as any)
const privateBackofficeConversationsPageRoute =
  privateBackofficeConversationsPageRouteImport.update({
    id: '/backoffice/conversations/',
    path: '/backoffice/conversations/',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateBackofficeGuestsPageRoute =
  privateBackofficeGuestsPageRouteImport.update({
    id: '/backoffice/guests/',
    path: '/backoffice/guests/',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateBackofficeHandoffsPageRoute =
  privateBackofficeHandoffsPageRouteImport.update({
    id: '/backoffice/handoffs/',
    path: '/backoffice/handoffs/',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateBackofficeQrSheetPageRoute =
  privateBackofficeQrSheetPageRouteImport.update({
    id: '/backoffice/qr-sheet/',
    path: '/backoffice/qr-sheet/',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateProfilePrivacyPageRoute =
  privateProfilePrivacyPageRouteImport.update({
    id: '/privacy/',
    path: '/privacy/',
    getParentRoute: () => privateProfileLayoutRoute,
  } as any)
const privateProfileSecurityPageRoute =
  privateProfileSecurityPageRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => privateProfileLayoutRoute,
  } as any)
const publicITokenPageRoute = publicITokenPageRouteImport.update({
  id: '/(public)/i/$token/',
  path: '/i/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateBackofficeConversationsConversationIdPageRoute =
  privateBackofficeConversationsConversationIdPageRouteImport.update({
    id: '/backoffice/conversations/$conversationId/',
    path: '/backoffice/conversations/$conversationId/',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateBackofficeGuestsGuestIdPageRoute =
  privateBackofficeGuestsGuestIdPageRouteImport.update({
    id: '/backoffice/guests/$guestId/',
    path: '/backoffice/guests/$guestId/',
    getParentRoute: () => privateLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/profile': typeof privateProfileLayoutRouteWithChildren
  '/screens/': typeof kioskScreensPageRoute
  '/': typeof privatehomePageRoute
  '/backoffice/': typeof privateBackofficePageRoute
  '/profile/': typeof privateProfilePageRoute
  '/forgot-password/': typeof guestauthForgotPasswordPageRoute
  '/login/': typeof guestauthLoginPageRoute
  '/reset-password/': typeof guestauthResetPasswordPageRoute
  '/screens/accueil/': typeof kioskScreensAccueilPageRoute
  '/screens/borne/': typeof kioskScreensBornePageRoute
  '/screens/discours/': typeof kioskScreensDiscoursPageRoute
  '/screens/operateur/': typeof kioskScreensOperateurPageRoute
  '/backoffice/conversations/': typeof privateBackofficeConversationsPageRoute
  '/backoffice/guests/': typeof privateBackofficeGuestsPageRoute
  '/backoffice/handoffs/': typeof privateBackofficeHandoffsPageRoute
  '/backoffice/qr-sheet/': typeof privateBackofficeQrSheetPageRoute
  '/profile/privacy/': typeof privateProfilePrivacyPageRoute
  '/profile/security/': typeof privateProfileSecurityPageRoute
  '/i/$token/': typeof publicITokenPageRoute
  '/backoffice/conversations/$conversationId/': typeof privateBackofficeConversationsConversationIdPageRoute
  '/backoffice/guests/$guestId/': typeof privateBackofficeGuestsGuestIdPageRoute
}
export interface FileRoutesByTo {
  '/screens': typeof kioskScreensPageRoute
  '/': typeof privatehomePageRoute
  '/backoffice': typeof privateBackofficePageRoute
  '/profile': typeof privateProfilePageRoute
  '/forgot-password': typeof guestauthForgotPasswordPageRoute
  '/login': typeof guestauthLoginPageRoute
  '/reset-password': typeof guestauthResetPasswordPageRoute
  '/screens/accueil': typeof kioskScreensAccueilPageRoute
  '/screens/borne': typeof kioskScreensBornePageRoute
  '/screens/discours': typeof kioskScreensDiscoursPageRoute
  '/screens/operateur': typeof kioskScreensOperateurPageRoute
  '/backoffice/conversations': typeof privateBackofficeConversationsPageRoute
  '/backoffice/guests': typeof privateBackofficeGuestsPageRoute
  '/backoffice/handoffs': typeof privateBackofficeHandoffsPageRoute
  '/backoffice/qr-sheet': typeof privateBackofficeQrSheetPageRoute
  '/profile/privacy': typeof privateProfilePrivacyPageRoute
  '/profile/security': typeof privateProfileSecurityPageRoute
  '/i/$token': typeof publicITokenPageRoute
  '/backoffice/conversations/$conversationId': typeof privateBackofficeConversationsConversationIdPageRoute
  '/backoffice/guests/$guestId': typeof privateBackofficeGuestsGuestIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(kiosk)': typeof kioskLayoutRouteWithChildren
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(guest)/(auth)': typeof guestauthLayoutRouteWithChildren
  '/(private)/profile': typeof privateProfileLayoutRouteWithChildren
  '/(kiosk)/screens/': typeof kioskScreensPageRoute
  '/(private)/(home)/': typeof privatehomePageRoute
  '/(private)/backoffice/': typeof privateBackofficePageRoute
  '/(private)/profile/': typeof privateProfilePageRoute
  '/(guest)/(auth)/forgot-password/': typeof guestauthForgotPasswordPageRoute
  '/(guest)/(auth)/login/': typeof guestauthLoginPageRoute
  '/(guest)/(auth)/reset-password/': typeof guestauthResetPasswordPageRoute
  '/(kiosk)/screens/accueil/': typeof kioskScreensAccueilPageRoute
  '/(kiosk)/screens/borne/': typeof kioskScreensBornePageRoute
  '/(kiosk)/screens/discours/': typeof kioskScreensDiscoursPageRoute
  '/(kiosk)/screens/operateur/': typeof kioskScreensOperateurPageRoute
  '/(private)/backoffice/conversations/': typeof privateBackofficeConversationsPageRoute
  '/(private)/backoffice/guests/': typeof privateBackofficeGuestsPageRoute
  '/(private)/backoffice/handoffs/': typeof privateBackofficeHandoffsPageRoute
  '/(private)/backoffice/qr-sheet/': typeof privateBackofficeQrSheetPageRoute
  '/(private)/profile/privacy/': typeof privateProfilePrivacyPageRoute
  '/(private)/profile/security/': typeof privateProfileSecurityPageRoute
  '/(public)/i/$token/': typeof publicITokenPageRoute
  '/(private)/backoffice/conversations/$conversationId/': typeof privateBackofficeConversationsConversationIdPageRoute
  '/(private)/backoffice/guests/$guestId/': typeof privateBackofficeGuestsGuestIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/screens/'
    | '/'
    | '/backoffice/'
    | '/profile/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/screens/accueil/'
    | '/screens/borne/'
    | '/screens/discours/'
    | '/screens/operateur/'
    | '/backoffice/conversations/'
    | '/backoffice/guests/'
    | '/backoffice/handoffs/'
    | '/backoffice/qr-sheet/'
    | '/profile/privacy/'
    | '/profile/security/'
    | '/i/$token/'
    | '/backoffice/conversations/$conversationId/'
    | '/backoffice/guests/$guestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/screens'
    | '/'
    | '/backoffice'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/screens/accueil'
    | '/screens/borne'
    | '/screens/discours'
    | '/screens/operateur'
    | '/backoffice/conversations'
    | '/backoffice/guests'
    | '/backoffice/handoffs'
    | '/backoffice/qr-sheet'
    | '/profile/privacy'
    | '/profile/security'
    | '/i/$token'
    | '/backoffice/conversations/$conversationId'
    | '/backoffice/guests/$guestId'
  id:
    | '__root__'
    | '/(kiosk)'
    | '/(private)'
    | '/(guest)/(auth)'
    | '/(private)/profile'
    | '/(kiosk)/screens/'
    | '/(private)/(home)/'
    | '/(private)/backoffice/'
    | '/(private)/profile/'
    | '/(guest)/(auth)/forgot-password/'
    | '/(guest)/(auth)/login/'
    | '/(guest)/(auth)/reset-password/'
    | '/(kiosk)/screens/accueil/'
    | '/(kiosk)/screens/borne/'
    | '/(kiosk)/screens/discours/'
    | '/(kiosk)/screens/operateur/'
    | '/(private)/backoffice/conversations/'
    | '/(private)/backoffice/guests/'
    | '/(private)/backoffice/handoffs/'
    | '/(private)/backoffice/qr-sheet/'
    | '/(private)/profile/privacy/'
    | '/(private)/profile/security/'
    | '/(public)/i/$token/'
    | '/(private)/backoffice/conversations/$conversationId/'
    | '/(private)/backoffice/guests/$guestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  kioskLayoutRoute: typeof kioskLayoutRouteWithChildren
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  guestauthLayoutRoute: typeof guestauthLayoutRouteWithChildren
  publicITokenPageRoute: typeof publicITokenPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(kiosk)': {
      id: '/(kiosk)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof kioskLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/(auth)': {
      id: '/(guest)/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestauthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/profile': {
      id: '/(private)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privateProfileLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(kiosk)/screens/': {
      id: '/(kiosk)/screens/'
      path: '/screens'
      fullPath: '/screens/'
      preLoaderRoute: typeof kioskScreensPageRouteImport
      parentRoute: typeof kioskLayoutRoute
    }
    '/(private)/(home)/': {
      id: '/(private)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatehomePageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/backoffice/': {
      id: '/(private)/backoffice/'
      path: '/backoffice'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof privateBackofficePageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/profile/': {
      id: '/(private)/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof privateProfilePageRouteImport
      parentRoute: typeof privateProfileLayoutRoute
    }
    '/(guest)/(auth)/forgot-password/': {
      id: '/(guest)/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof guestauthForgotPasswordPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(guest)/(auth)/login/': {
      id: '/(guest)/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof guestauthLoginPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(guest)/(auth)/reset-password/': {
      id: '/(guest)/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof guestauthResetPasswordPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(kiosk)/screens/accueil/': {
      id: '/(kiosk)/screens/accueil/'
      path: '/screens/accueil'
      fullPath: '/screens/accueil/'
      preLoaderRoute: typeof kioskScreensAccueilPageRouteImport
      parentRoute: typeof kioskLayoutRoute
    }
    '/(kiosk)/screens/borne/': {
      id: '/(kiosk)/screens/borne/'
      path: '/screens/borne'
      fullPath: '/screens/borne/'
      preLoaderRoute: typeof kioskScreensBornePageRouteImport
      parentRoute: typeof kioskLayoutRoute
    }
    '/(kiosk)/screens/discours/': {
      id: '/(kiosk)/screens/discours/'
      path: '/screens/discours'
      fullPath: '/screens/discours/'
      preLoaderRoute: typeof kioskScreensDiscoursPageRouteImport
      parentRoute: typeof kioskLayoutRoute
    }
    '/(kiosk)/screens/operateur/': {
      id: '/(kiosk)/screens/operateur/'
      path: '/screens/operateur'
      fullPath: '/screens/operateur/'
      preLoaderRoute: typeof kioskScreensOperateurPageRouteImport
      parentRoute: typeof kioskLayoutRoute
    }
    '/(private)/backoffice/conversations/': {
      id: '/(private)/backoffice/conversations/'
      path: '/backoffice/conversations'
      fullPath: '/backoffice/conversations/'
      preLoaderRoute: typeof privateBackofficeConversationsPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/backoffice/guests/': {
      id: '/(private)/backoffice/guests/'
      path: '/backoffice/guests'
      fullPath: '/backoffice/guests/'
      preLoaderRoute: typeof privateBackofficeGuestsPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/backoffice/handoffs/': {
      id: '/(private)/backoffice/handoffs/'
      path: '/backoffice/handoffs'
      fullPath: '/backoffice/handoffs/'
      preLoaderRoute: typeof privateBackofficeHandoffsPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/backoffice/qr-sheet/': {
      id: '/(private)/backoffice/qr-sheet/'
      path: '/backoffice/qr-sheet'
      fullPath: '/backoffice/qr-sheet/'
      preLoaderRoute: typeof privateBackofficeQrSheetPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/profile/privacy/': {
      id: '/(private)/profile/privacy/'
      path: '/privacy'
      fullPath: '/profile/privacy/'
      preLoaderRoute: typeof privateProfilePrivacyPageRouteImport
      parentRoute: typeof privateProfileLayoutRoute
    }
    '/(private)/profile/security/': {
      id: '/(private)/profile/security/'
      path: '/security'
      fullPath: '/profile/security/'
      preLoaderRoute: typeof privateProfileSecurityPageRouteImport
      parentRoute: typeof privateProfileLayoutRoute
    }
    '/(public)/i/$token/': {
      id: '/(public)/i/$token/'
      path: '/i/$token'
      fullPath: '/i/$token/'
      preLoaderRoute: typeof publicITokenPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/backoffice/conversations/$conversationId/': {
      id: '/(private)/backoffice/conversations/$conversationId/'
      path: '/backoffice/conversations/$conversationId'
      fullPath: '/backoffice/conversations/$conversationId/'
      preLoaderRoute: typeof privateBackofficeConversationsConversationIdPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/backoffice/guests/$guestId/': {
      id: '/(private)/backoffice/guests/$guestId/'
      path: '/backoffice/guests/$guestId'
      fullPath: '/backoffice/guests/$guestId/'
      preLoaderRoute: typeof privateBackofficeGuestsGuestIdPageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface kioskLayoutRouteChildren {
  kioskScreensPageRoute: typeof kioskScreensPageRoute
  kioskScreensAccueilPageRoute: typeof kioskScreensAccueilPageRoute
  kioskScreensBornePageRoute: typeof kioskScreensBornePageRoute
  kioskScreensDiscoursPageRoute: typeof kioskScreensDiscoursPageRoute
  kioskScreensOperateurPageRoute: typeof kioskScreensOperateurPageRoute
}

const kioskLayoutRouteChildren: kioskLayoutRouteChildren = {
  kioskScreensPageRoute: kioskScreensPageRoute,
  kioskScreensAccueilPageRoute: kioskScreensAccueilPageRoute,
  kioskScreensBornePageRoute: kioskScreensBornePageRoute,
  kioskScreensDiscoursPageRoute: kioskScreensDiscoursPageRoute,
  kioskScreensOperateurPageRoute: kioskScreensOperateurPageRoute,
}

const kioskLayoutRouteWithChildren = kioskLayoutRoute._addFileChildren(
  kioskLayoutRouteChildren,
)

interface privateProfileLayoutRouteChildren {
  privateProfilePageRoute: typeof privateProfilePageRoute
  privateProfilePrivacyPageRoute: typeof privateProfilePrivacyPageRoute
  privateProfileSecurityPageRoute: typeof privateProfileSecurityPageRoute
}

const privateProfileLayoutRouteChildren: privateProfileLayoutRouteChildren = {
  privateProfilePageRoute: privateProfilePageRoute,
  privateProfilePrivacyPageRoute: privateProfilePrivacyPageRoute,
  privateProfileSecurityPageRoute: privateProfileSecurityPageRoute,
}

const privateProfileLayoutRouteWithChildren =
  privateProfileLayoutRoute._addFileChildren(privateProfileLayoutRouteChildren)

interface privateLayoutRouteChildren {
  privateProfileLayoutRoute: typeof privateProfileLayoutRouteWithChildren
  privatehomePageRoute: typeof privatehomePageRoute
  privateBackofficePageRoute: typeof privateBackofficePageRoute
  privateBackofficeConversationsPageRoute: typeof privateBackofficeConversationsPageRoute
  privateBackofficeGuestsPageRoute: typeof privateBackofficeGuestsPageRoute
  privateBackofficeHandoffsPageRoute: typeof privateBackofficeHandoffsPageRoute
  privateBackofficeQrSheetPageRoute: typeof privateBackofficeQrSheetPageRoute
  privateBackofficeConversationsConversationIdPageRoute: typeof privateBackofficeConversationsConversationIdPageRoute
  privateBackofficeGuestsGuestIdPageRoute: typeof privateBackofficeGuestsGuestIdPageRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateProfileLayoutRoute: privateProfileLayoutRouteWithChildren,
  privatehomePageRoute: privatehomePageRoute,
  privateBackofficePageRoute: privateBackofficePageRoute,
  privateBackofficeConversationsPageRoute:
    privateBackofficeConversationsPageRoute,
  privateBackofficeGuestsPageRoute: privateBackofficeGuestsPageRoute,
  privateBackofficeHandoffsPageRoute: privateBackofficeHandoffsPageRoute,
  privateBackofficeQrSheetPageRoute: privateBackofficeQrSheetPageRoute,
  privateBackofficeConversationsConversationIdPageRoute:
    privateBackofficeConversationsConversationIdPageRoute,
  privateBackofficeGuestsGuestIdPageRoute:
    privateBackofficeGuestsGuestIdPageRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

interface guestauthLayoutRouteChildren {
  guestauthForgotPasswordPageRoute: typeof guestauthForgotPasswordPageRoute
  guestauthLoginPageRoute: typeof guestauthLoginPageRoute
  guestauthResetPasswordPageRoute: typeof guestauthResetPasswordPageRoute
}

const guestauthLayoutRouteChildren: guestauthLayoutRouteChildren = {
  guestauthForgotPasswordPageRoute: guestauthForgotPasswordPageRoute,
  guestauthLoginPageRoute: guestauthLoginPageRoute,
  guestauthResetPasswordPageRoute: guestauthResetPasswordPageRoute,
}

const guestauthLayoutRouteWithChildren = guestauthLayoutRoute._addFileChildren(
  guestauthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  kioskLayoutRoute: kioskLayoutRouteWithChildren,
  privateLayoutRoute: privateLayoutRouteWithChildren,
  guestauthLayoutRoute: guestauthLayoutRouteWithChildren,
  publicITokenPageRoute: publicITokenPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
